
### USUARIOS ###

GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvcmdlMTIzQGV4YW1wbGUuY29tIiwic3ViIjo2LCJpYXQiOjE3NDI0ODk1MjcsImV4cCI6MTc0MjQ5MzEyN30.mZaWAPfTvupOkJnXkcpWYJRMN89iqNirKLf-PlaBFo4




###


GET http://localhost:3000/users/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvYW9AZXhhbXBsZS5jb20iLCJzdWIiOjEsImlhdCI6MTc0MjM0NTcwNCwiZXhwIjoxNzQyMzQ5MzA0fQ.M8Za_xbu5k3sOSBCdaq_a8BOYj34A7MXnzLN8VcBxvs


###

POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvYW9AZXhhbXBsZS5jb20iLCJzdWIiOjEsImlhdCI6MTc0MjM0NTcwNCwiZXhwIjoxNzQyMzQ5MzA0fQ.M8Za_xbu5k3sOSBCdaq_a8BOYj34A7MXnzLN8VcBxvs


{
  "name": "jorge123",
  "email": "jorge123@example.com",
  "password": "123123"
}

###


PUT http://localhost:3000/users/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvYW9AZXhhbXBsZS5jb20iLCJzdWIiOjEsImlhdCI6MTc0MjM0NTcwNCwiZXhwIjoxNzQyMzQ5MzA0fQ.M8Za_xbu5k3sOSBCdaq_a8BOYj34A7MXnzLN8VcBxvs


{
  "name": "joaoteste",
  "email": "joaoteste@example.com",
  "password": "123"
}

###

DELETE http://localhost:3000/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvYW9AZXhhbXBsZS5jb20iLCJzdWIiOjEsImlhdCI6MTc0MjM0NTcwNCwiZXhwIjoxNzQyMzQ5MzA0fQ.M8Za_xbu5k3sOSBCdaq_a8BOYj34A7MXnzLN8VcBxvs




### EMPRESAS ###

GET http://localhost:3000/companies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvYW9AZXhhbXBsZS5jb20iLCJzdWIiOjEsImlhdCI6MTc0MjM0NTcwNCwiZXhwIjoxNzQyMzQ5MzA0fQ.M8Za_xbu5k3sOSBCdaq_a8BOYj34A7MXnzLN8VcBxvs



###

POST http://localhost:3000/companies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvYW9AZXhhbXBsZS5jb20iLCJzdWIiOjEsImlhdCI6MTc0MjM0NTcwNCwiZXhwIjoxNzQyMzQ5MzA0fQ.M8Za_xbu5k3sOSBCdaq_a8BOYj34A7MXnzLN8VcBxvs


{
  "name": "testando",
  "address": "tesstando102030"
}

###


DELETE http://localhost:3000/companies/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvYW9AZXhhbXBsZS5jb20iLCJzdWIiOjEsImlhdCI6MTc0MjM0NTcwNCwiZXhwIjoxNzQyMzQ5MzA0fQ.M8Za_xbu5k3sOSBCdaq_a8BOYj34A7MXnzLN8VcBxvs



### USER-EMPRESAS ###

GET http://localhost:3000/company-user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvYW9AZXhhbXBsZS5jb20iLCJzdWIiOjEsImlhdCI6MTc0MjM0NTcwNCwiZXhwIjoxNzQyMzQ5MzA0fQ.M8Za_xbu5k3sOSBCdaq_a8BOYj34A7MXnzLN8VcBxvs



###

POST http://localhost:3000/company-user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvYW9AZXhhbXBsZS5jb20iLCJzdWIiOjEsImlhdCI6MTc0MjM0NTcwNCwiZXhwIjoxNzQyMzQ5MzA0fQ.M8Za_xbu5k3sOSBCdaq_a8BOYj34A7MXnzLN8VcBxvs


{
  "userId": 1,
  "companyId": 2
}



### LOGIN ####

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "jorge123@example.com",
  "password": "123123"
}