
### USUARIOS ###

GET http://localhost:3000/users
Authorization: Bearer 




###


GET http://localhost:3000/users/3
Authorization: Bearer 


###

POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer 

{
  "name": "jorge123",
  "email": "jorge123@example.com",
  "password": "123123"
}

###


PUT http://localhost:3000/users/6
Content-Type: application/json
Authorization: Bearer 


{
  "name": "joaoteste",
  "email": "joaoteste@example.com",
  "password": "123"
}

###

DELETE http://localhost:3000/users/
Authorization: Bearer 




### EMPRESAS ###

GET http://localhost:3000/companies
Authorization: Bearer 



###

POST http://localhost:3000/companies
Content-Type: application/json
Authorization: Bearer 


{
  "name": "testando",
  "address": "tesstando102030"
}

###


DELETE http://localhost:3000/companies/5
Authorization: Bearer 



### USER-EMPRESAS ###

GET http://localhost:3000/company-user
Authorization: Bearer 



###

POST http://localhost:3000/company-user
Content-Type: application/json
Authorization: Bearer 


{
  "userId": 1,
  "companyId": 2
}



### LOGIN ####

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "jorge123@example.com",
  "password": "123123"
}